FROM jlesage/baseimage-gui:debian-8-v3.3.6
RUN apt-get update && apt-get install -y dbus libasound2 libdbus-glib-1-2 libgtk2.0-0 wget && apt-get autoclean
ADD firefox_config_eb1_am1_linux_64bit.tar.bz2 /config/.mozilla/
ADD firefox-38.0b1.tar.bz2 /usr/lib/
RUN ln -sf /usr/lib/firefox/firefox /usr/bin/firefox
# 添加一种服务,这里是firefox.
# COPY s6_firefox /etc/services.d/firefox/run
# 添加wget包和中文字体,镜像会变大一些.
# RUN apt-get update && apt-get install -y wget ttf-wqy-* && apt-get autoclean
COPY rc.xml /etc/xdg/openbox/rc.xml
COPY startapp.sh /startapp.sh
# RUN chmod +x /startapp.sh
ENV APP_NAME="Firefox 38"
# 设置环境变量,程序自动重启
ENV KEEP_APP_RUNNING=1
#ENV AM=0
